### PR TITLE
Issue #8: fix --no-upload command line option

### PR DESCRIPTION
**Pull request by PreludeAndFugue**
Changed the command line option to -u --upload, and the default
is not to upload test results to the pull request.

### CODE REVIEW

**Comment by PreludeAndFugue** [comment]
Mm. I guess there is a better way of doing this. The pull request has created a new issue. Perhaps should have assigned me to issue #8.

**Comment by certik** [comment]
Pull request always creates a new issue, don't worry about it. The patch is ok, except that I would like to have the default way to "upload". As that's how I use sympy-bot most of the time. Only for debugging, I set "--no-upload", so that I don't spam the sympy's pull requests. So the default options should reflect the most frequent usage. What do you think?

**Comment by PreludeAndFugue** [comment]
Yes, default option should reflect most frequent usage. I haven't really used it properly yet, and I have a few more issues which I will raise.

Just close this pull request to keep to the current behaviour.

**Comment by certik** [comment]
Sounds good. Definitely raise all the issues that you find. We need to keep improving it.

**Pull request closed without merging**
