### PR TITLE
Handle cleanly the case when pull["head"]["repo"] returns None.

### PR DESCRIPTION
**Pull request by jrioux**
This may be linked to the user sending a PR from his master branch.
For example, see https://github.com/sympy/sympy/pull/1793

### CODE REVIEW

**Comment by asmeurer** [comment]
I wonder if this is actually a github bug.

**Comment by certik** [comment]
This is +1 from me.

**Comment by jrioux** [comment]
Could be. I just know that it previously crashed my bot:

```
> Reviewing pull request #1793
Traceback (most recent call last):
  File "./sympy-bot", line 709, in <module>
    main()
  File "./sympy-bot", line 248, in main
    dispatch_reviews(options, urls, username=username, password=password, token=token)
  File "./sympy-bot", line 424, in dispatch_reviews
    repo_url = pull["head"]["repo"]["html_url"]
TypeError: 'NoneType' object is not subscriptable
```

and with this change it proceeds with the review.

**Comment by asmeurer** [comment]
Let's report it to @github just in case.

**Pull request merged**
