### PR TITLE
Added platform information to report's summary.

### PR DESCRIPTION
**Pull request by goodok**
So the python's version and architecture is showen in github
discussion directly. Like this:

```
Test results html report: http://reviews.sympy.org/report/agZzeW1weTNyDAsSBFRhc2sYv4YDDA

Summary: All tests have passed.

python: 2.6.6-final-0
architecture: Linux (64-bit)
cache: yes

Automatic review by sympy-bot.
```

In particular, it can help to others to decide with what versions
they can produce the additional test running.

Example of real usage of this is here:
https://github.com/sympy/sympy/pull/711#issuecomment-2718376

### CODE REVIEW

**Comment by asmeurer** [comment]
You example at that pull request shows that this is wrong.  It says it used Python 3, but the reported Python version is 2.6.

**Comment by goodok** [comment]
Yes,  it is because I ask version of python  which run the `sympy-bot` script, but the interpreter version, which sympy-bot run for the tests, is needed.

Now I have corrected this.

Now I coorect this, the python version info is obtained from interpretater by running
shell python script from sympy-bot:

```
cmd = "%s -c 'import sys; print(sys.version_info[:])'" % interpreter
```

with the help of `subprocess.Popen`. Then read output of this command.

The example outputs are here:

https://github.com/sympy/sympy/pull/233#issuecomment-2724665

**Comment by asmeurer** [comment]
OK, that looks better.  Just one more thing, then. I think it should not print that a custom interpreter was used any more, since this information is redundant.

By the way, does this work for PyPy?

**Comment by goodok** [comment]
Regarding PyPy, this doesn't work for it. Because its sys.version_info is not so compatible, as I thought.

I have pushed commit for this correction. The example report is here:

Regarding the warning note about custom interpretator, I donot know how to make the report exactly.
See the last report please: in my code I produce now only the version (without the path to the interpretor, I have removed it specially to do not show pathes), but the warning note give us additional info that it is PyPy.
On the same time this path shown at the report log [2].

May be produce version info summary as it is in [2] . (python version + executable). And then remove the warning note whether the custom interpreter is used or not. How do you think?

[1] https://github.com/sympy/sympy/pull/233#issuecomment-2725542
[2] http://reviews.sympy.org/report/agZzeW1weTNyDAsSBFRhc2sY7fMDDA

**Comment by asmeurer** [comment]
Let's just make none of it "warning notes", but just always tell what the interpreter was and what the test command was.  So something like

> ...
> _Interpreter:_ `python3`
> 
> _Test Command:_ `setup.py test`
> 
> **Summary:** All tests passed.
> ...

Because the **Note** makes it look like it is important, but actually, every single comment has it, so we might as well make it as if it were standard.

**Comment by goodok** [comment]
Summary's output have been reformatted (see: [1]). With the comparison of your's format I just have bolded the _`Test command:`_ string in the case of it is not equal to the default one, that is if the test process is not full.

[1] https://github.com/sympy/sympy/pull/233#issuecomment-2748725

**Comment by goodok** [comment]
Also this line was corrected in master: "not all arguments converted during string formatting"
https://github.com/sympy/sympy-bot/blob/master/sympy-bot#L122

**Comment by asmeurer** [comment]
This cannot be merged cleanly with master.

**Pull request merged**
