### PR TITLE
Print what pull request is being fetched

### PR DESCRIPTION
**Pull request by asmeurer**
Just a simple patch that makes things easier for my poor-man's tester scheme.

### CODE REVIEW

**Comment by asmeurer** [comment]
I'll also see about adding a fix for #140 later.

**Comment by asmeurer** [comment]
I added a commit fixing it. I don't plan on adding anything else.

**Comment by jrioux** [comment]
Is fetching `origin` always what we want or should we make use of the information we have in `merge_commit` (or whatever it's called)??

**Comment by asmeurer** [comment]
Fetching origin just pulls in the commits. The merge then happens against that pool. By default, it is against origin/master, so it does the right thing. I guess there's no way to make merge commit come from another source, but if I remember correctly it doesn't matter because if you use a local repo to aid cloning, it automatically pulls in all sha1s from that repo, even if they are from a separate remote. So you just have to do that and make sure it is in your local clone, and give the sha1.

**Comment by jrioux** [comment]
Good with me. +1

**Pull request merged**
