### PR TITLE
Morefixes

### PR DESCRIPTION
**Pull request by asmeurer**
Here some more various fixes.  Most of these come from the issues.

I'm still pushing stuff up, but feel free to review and merge at any time.

### CODE REVIEW

**Comment by certik** [comment]
Aaron, could you please rebase it? Sorry for forgetting to review it. If you rebase, I'll review now.

**Comment by asmeurer** [comment]
I've merged with master.

**Comment by asmeurer** [comment]
Something must be wrong with GitHub, since it's not showing that. But if you pull my branch, you should have a mergable version.

**Comment by asmeurer** [comment]
I guess they had some problems (see http://status.github.com/), but it all seems to be working now.

**Comment by certik** [comment]
Looks good, I merged it. Oops, tested it after the merge and:

<pre>
> Uploaded report at: http://pastehtml.com/view/b95mq6uh2.html
Traceback (most recent call last):
  File "./sympy-bot", line 386, in <module>
    main()
  File "./sympy-bot", line 79, in main
    review(int(arg2), options)
  File "./sympy-bot", line 373, in review
    review = formulate_review(report_url, report, user, testcommand)
NameError: global name 'testcommand' is not defined
</pre>


I'll fix it. Sorry about it, next time I should test before the merge.

**Comment by asmeurer** [comment]
Ah, that must have been an artifact of my merge with master, because it was working fine before that. I guess it needs to be `config.testcommand`.

**Comment by certik** [comment]
Fixed in f142e7e.

**Pull request merged**
