### PR TITLE
Add emoji symbols to the GitHub summary.  Closes #106.

### LINKED ISSUE #106: Make it clearer in the summary when a test has failed
Right now, the summary for a test failure looks too similar to the summary for tests passing.  They look the same, except for the summary text at the top.  It is too easy to miss a test failure if you aren't careful (like happened at sympy/sympy#1115).  

So we need to make it more prominent when tests failed.  One simple way would be to put the text "there were test failures" in bold, like

**Summary: There were test failures.**

It would be neat if we could use <FONT COLOR="#CCCCCC">colors</FONT>, but GitHub ignores html color tags.  Another idea would be to use some kind of colored symbol.  We could use emoji, like 

**Summary:** :star: All tests passed

and

**Summary:** :red_circle: There were test failures

(do those show up on non-Apple devices?).  See https://github.com/blog/816-emoji and http://www.emoji-cheat-sheet.com/

We could also include some kind of image, like 

**Summary:** Stop!</img> There were test failures.

### PR DESCRIPTION
**Pull request by asmeurer**
You now should see one of the following after **Summary** in the GitHub comments:

:exclamation: There were merge conflicts; could not test the branch.

:x: Could not fetch the branch.

:red_circle: There were test failures.

:eight_spoked_asterisk: All tests have passed.

See #106 for discussion about this.

### CODE REVIEW

**Comment by asmeurer** [comment]
I've got examples at sympy/sympy#715 and sympy/sympy#881 (I don't know how to reproduce the could not fetch error).

**Comment by certik** [comment]
I've seen this when you were testing it. I think this looks awesome.

**Comment by flacjacket** [comment]
So it seems @ness01 may have stumbled onto a way to reproduce the could not fetch error by testing a PR where the user has deleted the branch, which happened here:
https://github.com/sympy/sympy/pull/1234#issuecomment-5156882
I deleted the branch on github after it was merged.

**Comment by ness01** [comment]
(I misstyped the PR number, btw - sorry for stirring anything up)

**Pull request merged**
