### PR TITLE
Support GitHub two-factor authentication

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by asmeurer** [comment]
And by the way, if you're not using two-factor authentication, I highly recommend it, especially given the recent [GitHub password breach](https://github.com/blog/1698-weak-passwords-brute-forced). It's super easy to set up. Just click the button at https://github.com/settings/admin.

**Comment by certik** [comment]
I use two-factor authentication and I use application specific passwords, which should just work (I just type a specific long hash when it asks for a password).

**Comment by asmeurer** [comment]
Application specific passwords are a PITA in my opinion. They're also less secure than OTP codes generated by Google Authenticator or OAuth tokens.

**Comment by jrioux** [comment]
If it works for you, then +1.

**Pull request merged**
