### PR TITLE
Added support for Python 3

### PR DESCRIPTION
**Pull request by mattpap**

### CODE REVIEW

**Comment by certik** [comment]
I tested it, and I got:

<pre>
ondrej@eagle:~/repos/sympy-bot(mattpap-py3k)$ ./sympy-bot -3 review 631
Enter your GitHub username & password or press ^C to quit. The password
will be kept as a Python variable as long as sympy-bot is running and
https to authenticate with GitHub, otherwise not saved anywhere else:
Username: certik
Password: 
> Checking username and password ...
>     OK.
> Working directory: /tmp/sympy-bot-tmp4afZ_J
> Reviewing pull request #631
> Pull request info:
>     Author: "Mateusz Paprocki" <mattpap@gmail.com>
>     Repository: https://github.com/mattpap/sympy
>     Branch: has
> Cloning sympy/sympy master
Cloning into sympy...
remote: Counting objects: 49413, done.
remote: Compressing objects: 100% (12138/12138), done.
remote: Total 49413 (delta 39025), reused 46845 (delta 36834)
Receiving objects: 100% (49413/49413), 25.37 MiB | 628 KiB/s, done.
Resolving deltas: 100% (39025/39025), done.
> Running sympy-next
> checkout master: git checkout master
> reset tree: git reset --hard
> pull master: git pull https://github.com/sympy/sympy.git master
> switch to temporary branch: git checkout -b next-test
> Merging branch has from https://github.com/mattpap/sympy.
> Fetching branch has: git fetch https://github.com/mattpap/sympy has
> Merge branch has: git merge FETCH_HEAD
> Translating to Python 3 ... (this may take a few minutes)
Traceback (most recent call last):
  File "./sympy-next.py", line 436, in <module>
    main()
  File "./sympy-next.py", line 429, in main
    merges, tests = do_test(branches, "next-test")
  File "./sympy-next.py", line 164, in do_test
    pre_python3()
  File "./sympy-next.py", line 101, in pre_python3
    if subprocess.call(["python3", "bin/use2to3"], stdout=log, stderr=log) != 0:
  File "/usr/lib/python2.7/subprocess.py", line 486, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1213, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./sympy-bot", line 392, in <module>
    main()
  File "./sympy-bot", line 82, in main
    review(int(arg2), options)
  File "./sympy-bot", line 366, in review
    % (tmpdir, config.testcommand, python3))
  File "./sympy-bot", line 123, in cmd
    raise CmdException("Command '%s' failed with err=%d." % (s, r))
__main__.CmdException: Command 'cd /tmp/sympy-bot-tmp4afZ_J; ./sympy-next.py -r sympy -b branches -o out -l log --verbose --command "./setup.py test" -3' failed with err=256.
</pre>

**Comment by certik** [comment]
So it looks like it can't find the bin/use2to3, which however is in the bin directory of sympy. Hm. Any ideas?

**Comment by mattpap** [comment]
Do you have system wide `python3` (at least a symbolic link)?

**Comment by asmeurer** [comment]
It would be nice if it showed some progress when running use2to3.

**Comment by asmeurer** [comment]
But I guess this is a limitation in use2to3.  It needs a verbose option. I will open a SymPy issue for this.

**Comment by asmeurer** [comment]
This doesn't work correctly if you have a custom test command set (e.g., in a config file):

``` pytb

> Using /Users/aaronmeurer/.sympy/sympy-bot.conf
> Checking username and password ...
>     OK.
> Working directory: /var/folders/wc/dppcpmxs1tlb36nqcw853wkm0000gn/T/sympy-bot-tmpXmyG2f
> Reviewing pull request #630
> Pull request info:
>     Author: "Mateusz Paprocki" <mattpap@gmail.com>
>     Repository: https://github.com/mattpap/sympy
>     Branch: message
> Cloning sympy/sympy master
Cloning into sympy...
> Running sympy-next
> checkout master: git checkout master
> reset tree: git reset --hard
> pull master: git pull https://github.com/sympy/sympy.git master
> switch to temporary branch: git checkout -b next-test
> Merging branch message from https://github.com/mattpap/sympy.
> Fetching branch message: git fetch https://github.com/mattpap/sympy message
> Merge branch message: git merge FETCH_HEAD
> Translating to Python 3 ... (this may take a few minutes)
> Entering sympy-py3k
> Running unit tests.
> Command: python2.5 setup.py test
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    import sympy
  File "/private/var/folders/wc/dppcpmxs1tlb36nqcw853wkm0000gn/T/sympy-bot-tmpXmyG2f/sympy/sympy-py3k/sympy/__init__.py", line 21
    from .logic import *
SyntaxError: 'import *' not allowed with 'from .'
```

**Comment by asmeurer** [comment]
Also, it probably should "just work" if you do `-t "python3 setup.py test"`.  Perhaps the best thing to do would be to separate the test command from the executable in all the options.

**Comment by mattpap** [comment]
I changed the last commit. Now `-3` is just a shorthand for `-i python3`. The `-i` option allows to choose any interpreter and sympy-next pre-runs this interpreter and gather its version using `sys.version_info` and based on this, decides whether to translate SymPy to Python 3.

**Comment by certik** [comment]
I successfully tested the first two commits (2752e7e). If the rest works well for you Aaron, please push this in.

**Comment by certik** [comment]
(@mattpap, yes, I was missing the python3 executable, that was it.)

**Comment by certik** [comment]
There is one more problem. I was not able to find the converted files from the 2to3 run. The code quality in some pull request failed (trailing whitespace), so I wanted to check the file, but the file wasn't there...

**Comment by mattpap** [comment]
> I was not able to find the converted files from the 2to3 run.

They are automatically removed. However, I see that use2to3 is smart enough, so I can change this.

>  The code quality in some pull request failed (...)

Apparently 2to3 adds trailing whitespace. I fixed this here: https://github.com/sympy/sympy/pull/633

**Comment by certik** [comment]
So even the later patches work well for me, so I am merging it. Yes, let's keep the 2to3 generated files on the disk, so that one can debug it.

**Pull request merged**
