### PR TITLE
Add API token support

### PR DESCRIPTION
**Pull request by flacjacket**
Adds support for using the GitHub API v3 tokens.

### CODE REVIEW

**Comment by asmeurer** [comment]
This works great.  I'm testing it with sympy/sympy#1400 now.

My only suggestion is to add an interactive command to sympy-bot that asks for your username and gives you the token (and maybe even writes it to the config file for you).  

Also, this makes me a little sad that I'm going to have to remove my sympy-bot.conf from my [dotfiles](https://github.com/asmeurer/dotfiles) repo again, as I can't publish my token publicly.  Any thoughts on how that might be resolved?

**Comment by asmeurer** [comment]
I know you've changed the way the config file works in another PR, so maybe you could address this there, but it's very confusing how the config file should look from the readme (should there be quotes or no quotes, for example).  I would add a little "sample" config file to the readme that has actual things, like

```
username="johnsmith"
token="23fb18abf8bfe28db3808974719738797"
reference="~/path/to/local/sympy"
```

**Comment by flacjacket** [comment]
Well, currently the conf file is exec'ed to import it, so you could leave the token in another file and open it. Because it is exec'ed, it needs quotes. I'll update the README for it. In my other pull, I moved from exec'ing the file to using ConfigParser, tho this may be a good case for leaving it as is.

**Comment by asmeurer** [comment]
Oh I did not realize that.  It really ought to be called sympy-bot.conf.py then.

Will moving to ConfigParser make it easier to interactively write the config file? If so, we should weight that too.  It would be cool if after entering a username and password (for a new user), SymPy bot asked if you want to save the username and a token to the config file.  I suppose that should be possible even as it is now (the syntax isn't that complicated).

**Comment by asmeurer** [comment]
Another option would be to require the token to be in a separate file, and have the token parameter be the path of that file.  That way, we could support ConfigParser and my dotfiles repo.  It would be a little more work, but if we provide an interactive interface to automatically get and save the token, it won't matter.

I guess the question is, would there ever be a reason why someone would want the config file to be executable?  Perhaps some script that automatically gathers Python versions? But honestly, any feature I can thiink of we can just put directly into the bot (since this is just our personal testing project, it's no big deal).

By the way, what are the main advantages of ConfigParser?  More secure I suppose?

**Comment by flacjacket** [comment]
Creation and saving of both configuration files and tokens is now handled by the bot. If you password authenticate, it will run you through the token creation process. There is also a token_file option for storing the token separate from the main configuration.

My primary reason to change to ConfigParser was security. Also, the namespace from the exec call has a bunch of stuff in it and this way, the entire parsed dict can be set as the default values for args (rather than selecting which options will be taken from the config file) without polluting the result of parsing the args. I couldn't really think of a good application of being able to run scripts in the config file.

**Comment by asmeurer** [comment]
I'll play with this, but I just want to say that there's probably no reason to allow storing the password in the configuration file anymore. 

So I take it your plan is to go ahead with ConfigParser.

**Comment by flacjacket** [comment]
I know we don't have to be too careful about breaking things, so should we just drop passwords in configuration files now?

Yeah, I already have the change to ConfigParser in #115, unless someone has any objections or reasons not to change.

**Comment by asmeurer** [comment]
Yeah. I think support for saving the password in the config file was only added for compatibility when the old API stopped working anyway. 

And let's go ahead and move forward with ConfigParser.

**Comment by certik** [comment]
@asmeurer, @flacjacket, what is the status of this? Is it ready to be merged? I like the changes.

**Comment by flacjacket** [comment]
I have merged master with this branch and back to where using a token, in the conf file or a separate token_file, works fine, but there are still some things to work out with generating/updating a config file.

**Comment by flacjacket** [comment]
@asmeurer @certik Alright, I think it is working now, but someone else should test it first. You should back up your config file if you are worried about losing it. You'll need to change the `default` section to `DEFAULT`. It is supposed to be case-insensitive, but playing with it, I don't think it is.

**Comment by asmeurer** [comment]
Also we should try to get someone on windows to test this.

**Comment by certik** [comment]
I have access to windows. I will have to first figure out how to get the sympy-bot working there (I never tried it), then document it in README.rst and then try this PR.

**Comment by flacjacket** [comment]
Windows should just work (at least the current master), I added some Windows fixes to the previous pull. I'm at a conference all week, otherwise I could check the token works in Windows.

**Comment by asmeurer** [comment]
Sorry.  The reason I haven't tested this yet is that I was busy doing a little refactoring of my own, over at #123.

**Comment by asmeurer** [comment]
OK, now getting around to testing this.  What I've noticed so far:
- I chose Y to "Create config file", but this deleted all the comments from my config file.
- It should allow me to name the token (with the default "SymPy Bot (API)") so that I can change the name if I want (e.g., if I have multiple computers with SymPy Bot).
- I don't understand why default had to be renamed to DEFAULT.  This would have made things quite confusing for me if I hadn't known.

**Comment by asmeurer** [comment]
Hmm, based on my searching, preserving comments doesn't seem to be an easy task. There is a configobj external library that will do it, but I don't think it's worth it at this point to use a non-standard library module just for this.

You could try to add the variables manually.  It probably wouldn't be that difficult, given that you already know that the file is in correct configparser syntax.  Or just add a warning that writing to the config file will clear the comments, and if the user chooses no just tell him what lines he needs to add so he can do it manually.  And obviously if the config file doesn't already exist, then it's not an issue.

**Comment by asmeurer** [comment]
Got this error:

``` pytb
> Uploading the review to the GitHub pull request ...
Traceback (most recent call last):
  File "./sympy-bot", line 616, in <module>
    main()
  File "./sympy-bot", line 228, in main
    dispatch_reviews(options, urls, username=username, password=password)
  File "./sympy-bot", line 528, in dispatch_reviews
    review)
TypeError: github_add_comment_to_pull_request() takes exactly 6 arguments (5 given)
```

**Comment by certik** [comment]
@flacjacket, are you getting the same error?

Let's get this in after it works.

**Comment by flacjacket** [comment]
Sorry, lab has been busy this week. I don't remember getting that, but I'll take a look when I get home tonight.

**Comment by flacjacket** [comment]
Got some time to work it out. This should work now.

@asmeurer: Yes, using ConfigParser, any comments/formatting is lost, I don't really think there is much that can be done about that using ConfigParser to write files. I can write something that tries to parse the file and insert the line in the correct position. This would also mean this could go back to using `default` rather than needing `DEFAULT`. I think it's an upstream problem, but it seems like `DEFAULT` is always recognized as the default section, while for some operations `default` is recognized as a section called "default". I haven't tested thoroughly enough to say for sure.

I also added an option to change the name of the tokens as they appear on https://github.com/settings/applications.

**Comment by asmeurer** [comment]
I came to the same conclusion.  I would just print the warning as I noted above, and show the user what to do if he chooses no.

**Comment by certik** [comment]
@asmeurer, please merge this if you are +1 to it. I like this branch.

**Comment by asmeurer** [comment]
OK. Let me test it again.

**Comment by flacjacket** [comment]
I added the warning message now, as well.

**Comment by asmeurer** [comment]
Thanks.  I'm merging this...

**Pull request merged**
