### PR TITLE
Limit access to cronjob pages issue #99

### PR DESCRIPTION
**Pull request by MichaelMayorov**
Fix for issue #99

### CODE REVIEW

**Comment by asmeurer** [comment]
@certik can you review this.

Also, can you give me access to the reviews site, SymPy Gamma, and any other SymPy AppEngine pages that you may have created?

**Comment by MichaelMayorov** [comment]
I've created test project with my changes http://sympy-bot-test.appspot.com/

URLs for testing:
http://sympy-bot-test.appspot.com/update
http://sympy-bot-test.appspot.com/quickupdate

theese pages should ask for admin account to prevent everyone from launching cron scripts.

**Comment by asmeurer** [comment]
So assumedly when you go there, as an admin, it actually does the update?

**Comment by MichaelMayorov** [comment]
yes, it does.

**Comment by MichaelMayorov** [comment]
Also, seems like I forgot to write steps of reproduce.
1. Open http://reviews.sympy.org/update
2. Press F5
3. move to 2 for 10-20 times
   ...

4 DoS :)

**Comment by asmeurer** [comment]
Is F5 something that's built into the app, or is this something that does reload in your browser?

**Comment by MichaelMayorov** [comment]
oh, sorry. Of course I mean browser

**Comment by asmeurer** [comment]
I've merged this.  I'll update the reviews site momentarily...

**Comment by asmeurer** [comment]
OK, this is now live.  Let me know if there are any problems, and I can roll it back.

**Comment by MichaelMayorov** [comment]
Yeah, I see this, thanks.
Did you try to run cron job ( reviews.sympy.org/update or reviews.sympy.org/quickupdate ) as admin?

**Comment by certik** [comment]
Cool, thanks for the fix. I think it works. Yes, these pages should be protected.

**Pull request merged**
