### PR TITLE
Python

### PR DESCRIPTION
**Pull request by asmeurer**
This lets you specify a custom test command to run the tests with.  This lets you run the tests with a different Python than the default. I recommend that everyone add `testcommand = "python2.5 setup.py test"` to their `~/.sympy/sympy-bot.conf` file.

I also added some small unrelated fixes that I made along the way.

### CODE REVIEW

**Comment by asmeurer** [comment]
Technically, you can also use this to do things like only run the doctests or only run a specific test.  I would recommend against this though (this is yet another reason why you should always double check against the html report before merging an apparently clean branch).

**Comment by asmeurer** [comment]
Please close #20 when you merge this.

I thought of another use for this: the ability to run the tests in Python 3 when that is ready.

**Comment by certik** [comment]
This is fine with me. I don't have time currently to test this (going to Prague tomorrow), so if it works, feel free to push it in.

**Comment by vperic** [comment]
@certik, if you've got time, feel free to drop me a mail! I'm also in Prague.

**Pull request merged**
