### PR TITLE
Better html output

### PR DESCRIPTION
**Pull request by ness01**
Hi,

I changed the output generation so as to group tests, doctests, and documentation tests separately, and also include a summary line as you suggested.

Regards,
Tom

### CODE REVIEW

**Comment by certik** [comment]
I have just tested it, and it works! So I am merging this. Thanks!

**Comment by asmeurer** [comment]
@ness01, don't forget to not commit over master.

**Comment by ness01** [comment]
What's wrong with that?

**Comment by asmeurer** [comment]
There are a few reasons:
- Basically, master is reserved to be the official master branch.
- Strictly speaking, if you are committing over master, you can only make one fix at a time.
- If someone pushes something else into the official master, your master will no longer be able to fast forward to it.  In this case, you were lucky, because your fix got pushed in right away.  What git will do if you do this is merge your changes with the other changes, which can result in a lot of merges. And again, this won't be the official master.  

The correct way to do it is to make a branch. git makes branching very easy, so you should take advantage of that.

If you are doing just a one man project in git (like a homework assignment), then it's perfectly fine to commit over master.  But when you have a workflow like we do where there is an official repo and you have to review changes to push to it, you should use branches.

**Comment by ness01** [comment]
Ok. Makes sense. I will keep it in mind.

**Pull request merged**
