### PR TITLE
Workaround script for testing all mergeable and *untested* pull requests.

### PR DESCRIPTION
**Pull request by Krastanov**
The script uses the github api to check wich pr are mergeable (the same as `sympy review mergeable`) and **not
yet tested** (this isn't implemented in sympy-bot yet). Then it runs sympy-bot on them.

The solution is very ugly. The way to use the script is just to start it
from your sympy-bot directory.

### CODE REVIEW

**Comment by asmeurer** [comment]
If this script works for you, that's great, but I wouldn't even merge it, because it doesn't generalize to multiple computers very well.  We really need is to have a queue system like described in #63 and on the mailing list.

**Comment by Krastanov** [comment]
I'm aware that it will not get merged. That's why I have called it a workaround. It's here just so if somebody wants to donate some processing power he can do it. But I don't think it will be necessary for the near future as it already runs on my computer and it's sufficiently fast to test all open pull requests in a day. For the moment I'm testing only on 2.7.1, tell me if you want to add other versions.

**Comment by asmeurer** [comment]
But the problem is that really only one person (you) can done processing power with this script.  Anything else will just generate duplicate reviews.

**Comment by Krastanov** [comment]
Whoever has the time can cherrypick this and create a real solution.

**Comment by certik** [comment]
Btw, are you aware of this?

```
$ sympy-bot list-numbers
> Using /home/ondrej/.sympy/sympy-bot.conf
Patches that cannot be merged without conflicts:
233 239 343 359 389 444 447 456 504 543 563 573 579 598 677 684 740 749 810

--------------------------------------------------------------------------------
Patches that can be merged without conflicts:
268 422 525 531 533 609 618 622 664 673 690 692 700 713 715 720 722 724 726 747 748 764 772 773 785 786 787 789 790 793 794 795 797 798 801 805 807 808 811 812 813 814 815 816 817
```

and this:

```
$ sympy-bot review 268 422 525 531 533 609 618 622 664 673 690 692 700 713 715 720 722 724 726 747 748 764 772 773 785 786 787 789 790 793 794 795 797 798 801 805 807 808 811 812 813 814 815 816 817
```

I think it implements exactly what you did in the script, just in a nice way. If that is what you want, then it is easy to create a new command, "review-mergeable-pullrequests" into our sympy-bot.

**Comment by Krastanov** [comment]
Yeah, I'm aware of those but those do not check if tests were already ran
on the latest branch head. And again, I'm not proposing that this should be
merged. It's here so if anybody chooses to implement the idea Aaron has
about distributed testing he can start somewhere. The thing that should be
changed is the ugly function in the script. If that function queries
reviews.sympy.org it would be just a trivial change to implement the
distributed stuff. And yeah, when this stuff is written it should be just a
command for sympy bot.

2011/12/4 Ondřej Čertík <
reply@reply.github.com

**Comment by Krastanov** [comment]
And of course instead of repeating code by using the github api it should use the functionality in sympy-bot. But for a one-time script the first was easier.

**Comment by certik** [comment]
Ah, I missed the part about the check about tests being run. Absolutely, thanks for posting the script here. We should refactor it and integrate into sympy-bot in some form.

**Comment by certik** [comment]
I forgot again about finding the latest branch hash. So I am reopening this. I changed the description to make this very clear.

**Comment by Krastanov** [comment]
How can I close the pull request but leave the issue open?

 As there is now work underway to fix this there is no need for this workaround. And as the idea behind the workaround is not at all a stable solution this code is not useful anymore.

**Comment by certik** [comment]
Just do Close pull request, then you need to open a new issue for it. I am closing it.

**Pull request closed without merging**
