### PR TITLE
Refactor how multiple reports are generated.

### PR DESCRIPTION
**Pull request by jrioux**
In case of merge conflicts: Abort trying to build the docs, upload only one merge conflict report instead of one per interpreter, and write a short to-the-point summary.

In case of an unfetchable branch: Similar, but no report necessary.

The diff for this looks worse than it actually is because of indentation: I had to wrap the tests in a `if` block. One can nicely see the meaningful changes with `git diff -b`.

### CODE REVIEW

**Comment by asmeurer** [comment]
Or https://github.com/sympy/sympy-bot/pull/136/files?w=1

**Comment by asmeurer** [comment]
That didn't work. I mean add "?w=1" to the end of the URL of the diff.

**Comment by jrioux** [comment]
I'll merge this in 24h if there are no more comments.

**Comment by asmeurer** [comment]
I didn't get a chance to review this, but I'm +1 if it works.

**Comment by asmeurer** [comment]
Actually, I just did test it, and it works.  I didn't test fetch, but I'll assume that it works too.

**Pull request merged**
