### PR TITLE
Change icon for tests that passed

### PR DESCRIPTION
**Pull request by vramana**
Changed the icon from :eight_spoked_asterisk:  to :white_check_mark:

### CODE REVIEW

**Comment by vramana** [comment]
@asmeurer

**Comment by asmeurer** [comment]
Ah other opinions on this? I'm fine either way.

**Comment by vramana** [comment]
@asmeurer  This is what I have found http://www.emoji-cheat-sheet.com/. I thought it is the best available.

**Comment by flacjacket** [comment]
I think this is fine, merging

**Pull request merged**
