### PR TITLE
Fixes #75

### LINKED ISSUE #75: master_hash missing on unmergeable PRs causing a crash
```
Auto-merging doc/src/modules/assumptions/index.txt
Auto-merging sympy/core/expr.py
CONFLICT (content): Merge conflict in sympy/core/expr.py
Automatic merge failed; fix conflicts and then commit the result.
Done.

View log at: /tmp/sympy-bot-tmpmSdoXH/out/log
Traceback (most recent call last):
  File "./sympy-bot", line 279, in <module>
    main()
  File "./sympy-bot", line 97, in main
    review(n, options)
  File "./sympy-bot", line 244, in review
    master_hash = result["master_hash"]
KeyError: 'master_hash'
```

### PR DESCRIPTION
**Pull request by certik**
This should fix it. I only tested it on a simple pull request that can be merged and one that cannot, without the actual upload.

### CODE REVIEW

**Comment by Krastanov** [comment]
It looks good, but I have not checked the code in depth. I'm already using this version in my automated testing script and now it does not crash because of sympy-bot (it crashes for other reasons).

+1

**Comment by certik** [comment]
Thanks for the review!

**Comment by asmeurer** [comment]
If the other reasons are SymPy related, open issues for them as well.

**Comment by Krastanov** [comment]
No, their are related to the poor quality of my script (mainly internet connection errors).

**Pull request merged**
